### ISSUE TITLE
Incorrect placing of glass in A-frame crate

### ISSUE THREAD

**Issue by JelmerDL** [treeDiM/MHBCrateLoadDesigner#12]
Glass should in any case be rotated to be placed on the long side. In this case, panes should have been rotated 90-degrees.

![image](https://user-images.githubusercontent.com/78344754/109975895-6d75bc00-7cfb-11eb-8cb6-3a72f493132b.png)

**Comment by fgasnier71** [comment]
See crate 4.
Glass panes need to be rotated 90°.

**Comment by fgasnier71** [comment]
@JelmerDL can you provide (either name or send) the input file that allows reproducing this bug.

**Comment by JelmerDL** [comment]
> @JelmerDL can you provide (either name or send) the input file that allows reproducing this bug.

@fgasnier71 see attached file.

[Puidelen (6) 16 units.xlsx](https://github.com/treeDiM/MHBCrateLoadDesigner/files/6091373/Puidelen.6.16.units.xlsx)
