### ISSUE TITLE
Incorrect placing of small glass crates

### ISSUE THREAD

**Issue by JelmerDL** [treeDiM/MHBCrateLoadDesigner#14]
Crates should be rotated 90-degrees (long side of crate along long side of container).
Crates should fit next to eachother, than after eachother.

![image](https://user-images.githubusercontent.com/78344754/109976526-276d2800-7cfc-11eb-98bb-ff7b32a056f3.png)

In this case it is correct/permitted to rotate the glass crate however:

![image](https://user-images.githubusercontent.com/78344754/110093761-5e464b00-7d9b-11eb-824f-ff7270519093.png)

**Comment by fgasnier71** [comment]
Whenever possible (limitation is the height), identical crates should be stacked on each other.
