### ISSUE TITLE
Incorrect stuffing

### ISSUE THREAD

**Issue by JelmerDL** [treeDiM/MHBCrateLoadDesigner#19]
Small glass crates from container 3, should have been stuffed into containers 1 and 2.

If (container height) > (sum height crates) : identical crates should be stacked on top of each other.

Container 1:
![image](https://user-images.githubusercontent.com/78344754/110100274-84bbb480-7da2-11eb-81b6-ec3dd1bbb39f.png)

Container 2:
![image](https://user-images.githubusercontent.com/78344754/110100361-9b620b80-7da2-11eb-87e0-4c89ca27aea1.png)

Container 3:
![image](https://user-images.githubusercontent.com/78344754/110100396-a6b53700-7da2-11eb-8ed4-056058851213.png)

**Comment by fgasnier71** [comment]
@JelmerDL Can you share the file used so that I test the fix written before uploading version 0.5.0.0 today?

**Comment by fgasnier71** [comment]
![image](https://user-images.githubusercontent.com/1512039/110615770-0ee58d80-8194-11eb-9b9c-ecb81deeb28d.png)

Done!
