### ISSUE TITLE
Incorrect stacking of crate

### ISSUE THREAD

**Issue by JelmerDL** [treeDiM/MHBCrateLoadDesigner#2]
Glas crates should always be stacked centered from the middle (equal weight distribution). Bottom center of "length" of crate:
![image](https://user-images.githubusercontent.com/78344754/107489972-8d491280-6b89-11eb-8141-d1eea7c1e958.png)

**Comment by fgasnier71** [comment]
Small glass crate 3 : in the back end,
Crate 4 5 6: in the middle center,

**Comment by fgasnier71** [comment]
4, 5, 6 are actually A-frames and the issue seems to be corrected.
