### ISSUE TITLE
Part-list output: data is written in header

### ISSUE THREAD

**Issue by JelmerDL** [treeDiM/MHBCrateLoadDesigner#20]
Data is written in header of table.

![image](https://user-images.githubusercontent.com/78344754/111154805-e7c3fd00-8593-11eb-8f4a-6f5415ee78cf.png)

**Comment by fgasnier71** [comment]
@JelmerDL The first sheet is different than the following sheets as it has an additional row at the top which makes array filling start at row 19 instead of 18.
Should the first sheet always be filled differently than following sheet i.e. with an offset in rows?

**Comment by JelmerDL** [comment]
> Should the first sheet always be filled differently than following sheet i.e. with an offset in rows?

@fgasnier71 I'll provide you with a new and corrected template. Is it an option that I'll just provide one tab and you copy tabs for every crate?

**Comment by fgasnier71** [comment]
> @fgasnier71 I'll provide you with a new and corrected template. Is it an option that I'll just provide one tab and you copy tabs for every crate?
Yes! Please do provide only the first sheet and I will copy it for each crate, making the code as simple as possible.

**Comment by JelmerDL** [comment]
@fgasnier71 
See attached file. Please note that this section needs to be filled by the software as well:
![image](https://user-images.githubusercontent.com/78344754/111446449-b589db00-870c-11eb-924b-9246b006766a.png)

[PROD.OrderStroom.7 - Part-list  Malfunctioning Export MHB.xlsx](https://github.com/treeDiM/MHBCrateLoadDesigner/files/6155233/PROD.OrderStroom.7.-.Part-list.Malfunctioning.Export.MHB.xlsx)

**Comment by fgasnier71** [comment]
@JelmerDL
**Note 1**: I will leave crate weight to 0 as you previously asserted that weight does not need to be computed in the application and only actual measured weight is to be used. Please confirm.
**Note 2**: Can you confirm that Crate 9 and the following are entered in sheet 2 "Arrival Check"?

**Comment by JelmerDL** [comment]
> @JelmerDL
> **Note 1**: I will leave crate weight to 0 as you previously asserted that weight does not need to be computed in the application and only actual measured weight is to be used. Please confirm.
> **Note 2**: Can you confirm that Crate 9 and the following are entered in sheet 2 "Arrival Check"?

Note 1: Correct and confirmed
Note 2: I believe that after crate 8, the arrival check should be numbered 9 to 16 and so on.
