### ISSUE TITLE
"Brand" field should not be unique

### ISSUE THREAD

**Issue by JelmerDL** [treeDiM/MHBCrateLoadDesigner#24]
![image](https://user-images.githubusercontent.com/78344754/114991317-bb084b80-9e99-11eb-99a8-814de8382f91.png)

May consist of multiple lines with frames and glass

**Comment by fgasnier71** [comment]
@JelmerDL  Can you confirm that the issue will be solved when the software does not check for an existing "unit" with the same id hence, allowing the same id to repeat in the item list?

**Comment by JelmerDL** [comment]
@fgasnier71 confirmed.
