### ISSUE TITLE
Container tab is not refreshed

### ISSUE THREAD

**Issue by JelmerDL** [treeDiM/MHBCrateLoadDesigner#26]
The container tab is not automatically refreshed when adding frames manually, thus creating more crates.
![image](https://user-images.githubusercontent.com/78344754/114992072-a11b3880-9e9a-11eb-8af4-208b79d20c66.png)

**Comment by fgasnier71** [comment]
@JelmerDL  Can you advise on what you expect the software to do if:
- glass/frames are added,
- the user already has manually modified a layer/crate or containers?

The software ought to:
1. recompute everything losing what user has manually modified,
2. warn the user that he might lose some manual editions he made,
3. try to fit new glass/frames in the crates but without modifying any previously edited layer, without any preexisting layers being moved in other crates, without modifying any edited container layout except by adding crates when possible.

**Comment by JelmerDL** [comment]
@fgasnier71 1 and 2. Recompute, but warn that any manual edits will be gone. A textline in the statusbar of the dialogbox will be enough.

![image](https://user-images.githubusercontent.com/78344754/115032450-9cba4400-9ec9-11eb-8ad3-d9a7d928c685.png)

**Comment by fgasnier71** [comment]
Corrected issue.
Please note that we can not rely on status bar warnings when removing frames and glass.
I decided that the software should use a warning message box.
