### ISSUE TITLE
Incorrect container for Crate 6 (extreme size glass crate)

### ISSUE THREAD

**Issue by JelmerDL** [treeDiM/MHBCrateLoadDesigner#27]
Glass larger than 4500x2150mm but smaller than 5000x2800mm should always go into crate 6.
Crate 6 should always try to fit in a 20'Open top container, or if it doesn't fit/multiple crate 6, in a 40'Open top container.

![image](https://user-images.githubusercontent.com/78344754/115412813-f8037380-a1f4-11eb-8ca4-b8888d24351d.png)

![image](https://user-images.githubusercontent.com/78344754/115412927-136e7e80-a1f5-11eb-9a87-96b323fa1282.png)

**Comment by fgasnier71** [comment]
@JelmerDL Can you provide the sample input that led to this result?

**Comment by JelmerDL** [comment]
@fgasnier71 
[puidelen Lot 338 - aangepast.xlsx](https://github.com/treeDiM/MHBCrateLoadDesigner/files/6459028/puidelen.Lot.338.-.aangepast.xlsx)

I believe it was this one.
