### ISSUE TITLE
Auto update feature 

### ISSUE THREAD

**Issue by JelmerDL** [treeDiM/MHBCrateLoadDesigner#29]
@fgasnier71 

Is it possible to roll out automatic updates to the program (or let the program check for new updates), without the need for an administrator to authorize the updates?

**Comment by fgasnier71** [comment]
I can add an auto-update feature easily (actually the same that is used in StackBuilder).

The other part is difficult to answer as I have no knowledge as to which security limitations are implemented on your machines.
Is StackBuilder allowed to update itself automatically on your machine?
If not, you will need to check with your administrator if he can allow some specific msi installation to occur without authorization.

**Comment by JelmerDL** [comment]
Sounds great, please add that if possible.

After installation I don't believe I need authorization with updates on Stackbuilder, however if that should be the case, we'll figure it out here with the administrator.
