### ISSUE TITLE
Incorrect stacking of A-frame

### ISSUE THREAD

**Issue by JelmerDL** [treeDiM/MHBCrateLoadDesigner#3]
A-frames should be stacked alternately descending, starting from the middle. Always bottom centered for weight distribution.

![image](https://user-images.githubusercontent.com/78344754/107490661-75be5980-6b8a-11eb-8b2c-8f919cd7896d.png)

**Comment by fgasnier71** [comment]
Crates 4-5 : see A-frames mention.
