### ISSUE TITLE
Defining the operation of manual editing of containers

### ISSUE THREAD

**Issue by fgasnier71** [treeDiM/MHBCrateLoadDesigner#32]
@JelmerDL
**How should the UI allow (re)defining the loading of crates in containers?**

**Proposal:**
- in a single form show a 2D top view of all containers with crates.
- allow the user to insert new containers,
- allow the user to move crate inside the container,
- allow 90° rotation via the context menu,
- allow the user to move crates from container to container,
- high crates are not allowed to be dropped in low roof containers,

**Limitations:**
- stacked crates would not be handled easily,
- the higher the number of containers, the lower the definition for moving containers. Would probably work fine with up to 10 containers.

**Choices to be made:**
1.  Either prevent user to drop crate in impossible location (e.g. outside of any container, overlapping another crate...)
meaning that the crate is brought back to its original drag location.
or prevent closing form if some errors are spotted displaying a list of errors.

Note: The first option might imply creating a temporary container to be able to move crates when all containers are nearly full.

2. How should stacked crates be handled. Do we need to unstack them before being able to drop them on another crate when possible?

**Comment by JelmerDL** [comment]
@fgasnier71 

> * in a single form show a 2D top view of all containers with crates.
> * allow the user to insert new containers,
> * allow the user to move crate inside the container,
> * allow 90° rotation via the context menu,
> * allow the user to move crates from container to container,

Yes to all of the above.

> * high crates are not allowed to be dropped in low roof containers,

True, except I believe we decided early on to have the opportunity to manually "chop" crate 1 to size (lower height from 2550mm to 2250mm) if not entirely full.

> **Limitations:**
> 
> * stacked crates would not be handled easily,

How about this?

![image](https://user-images.githubusercontent.com/78344754/116511632-03c2fa00-a8c7-11eb-9dd9-af03b55b1340.png)

- A label on the crate indicating the number of crate layers. 
- Change color if stacking isn't possible (height container - height placed crate - 130mm < height smallest remaining crate).


> * the higher the number of containers, the lower the definition for moving containers. Would probably work fine with up to 10 containers.
> 
> **Choices to be made:**
> 
> 1. Either prevent user to drop crate in impossible location (e.g. outside of any container, overlapping another crate...)
>    meaning that the crate is brought back to its original drag location.
>    or prevent closing form if some errors are spotted displaying a list of errors.
> Note: The first option might imply creating a temporary container to be able to move crates when all containers are nearly full.

First option would make the most sense. So no dropping in impossible location. An extra 'storage' location to temporary place crates would be helpful indeed, it doesn't necessarily need to be a container. Perhaps something like this:

![image](https://user-images.githubusercontent.com/78344754/116513797-6669c500-a8ca-11eb-98b6-dc5f08c03bba.png)

When unplaced crates remain, there should always be container space left to place it in or at least the possibility to manually add a new container.

> 1. How should stacked crates be handled. Do we need to unstack them before being able to drop them on another crate when possible?

Yes.
