### ISSUE TITLE
Incorrect container solution with stacked crates

### ISSUE THREAD

**Issue by JelmerDL** [treeDiM/MHBCrateLoadDesigner#33]
1) This stack of crates exceed container height and is an incorrect solution:

![image](https://user-images.githubusercontent.com/78344754/116541527-d76da480-a8eb-11eb-87c8-702dd76aa71c.png)

2) However, in the same case, there is one crate that could have been lowered to 2250mm and the whole order would still have fit into a 40'HC and 20'Box container:

![image](https://user-images.githubusercontent.com/78344754/116541693-13086e80-a8ec-11eb-9c39-a1c70874442f.png)

Issue (1) should not occur. 
Issue (2) is allowed to occur with the automated solution, however perhaps this is something we could manually change?

I've included order source file: 
[Puidelen 01235.xlsx](https://github.com/treeDiM/MHBCrateLoadDesigner/files/6398090/Puidelen.01235.xlsx)

**Comment by fgasnier71** [comment]
@JelmerDL This occurs because of downsizing from half-full 40HC to 20Box.
What should we do?
1. Prevent downsizing when it is not possible,
2. Use an open-top container 20.

**Comment by JelmerDL** [comment]
> @JelmerDL This occurs because of downsizing from half-full 40HC to 20Box.
> What should we do?
> 
> 1. Prevent downsizing when it is not possible,
> 2. Use an open-top container 20.

It should not stack because height of 2 glasscrates > inside height 20' container.
In this case, it should take a 40'HC because you'll have 2 crates remaining after filling the 20'box.
Less containers is always the most economical solution.
