### ISSUE TITLE
Empty crate (after manual editing)

### ISSUE THREAD

**Issue by JelmerDL** [treeDiM/MHBCrateLoadDesigner#36]
An empty crate after manual editing should be omitted or be manually removable. 

Example case: 
[Puidelen 05369.xlsx](https://github.com/treeDiM/MHBCrateLoadDesigner/files/6499588/Puidelen.05369.xlsx)

Crate 4 contains a single frame and I decide to manually move it to another crate to save space:
![image](https://user-images.githubusercontent.com/78344754/118618123-961e3580-b7c3-11eb-981a-49e993282561.png)

Crate 4 is now empty but will remain in use and still is part of the stowing solution:
![image](https://user-images.githubusercontent.com/78344754/118618385-d978a400-b7c3-11eb-9ee7-46d0db77a93f.png)
![image](https://user-images.githubusercontent.com/78344754/118618404-e09fb200-b7c3-11eb-8c48-f27ba4cb8a2b.png)

**Comment by fgasnier71** [comment]
@JelmerDL Do we need to be able to recreate a crate after it is removed?
e.g. the user might change mind?

**Comment by JelmerDL** [comment]
Yes, some sort of undo is desirable so that a user doesn't need to do over the whole project.
