### ISSUE TITLE
Similar glass distributing over different crates

### ISSUE THREAD

**Issue by JelmerDL** [treeDiM/MHBCrateLoadDesigner#6]
Best practice of sorting would be the smallest glass as much in the small glass crate instead of putting it in A-frame first. 

Keep similar sizes together as much as possible.

![image](https://user-images.githubusercontent.com/78344754/107493842-60e3c500-6b8e-11eb-9141-969b9602198c.png)

![image](https://user-images.githubusercontent.com/78344754/107493910-70fba480-6b8e-11eb-8845-e4053bc88cd5.png)

**Comment by fgasnier71** [comment]
How the stacking algorithm needs to be modified in the next release:
- first, proceed as currently by stacking in decreasing size and instantiating crates as they are needed,
- then, stack by increasing size in the existing crates.
This should result in moving more glass/frames in the smaller crates without creating unneeded crates.
