### ISSUE TITLE
Input extra parts box

### ISSUE THREAD

**Issue by JelmerDL** [treeDiM/MHBCrateLoadDesigner#7]
An extra tab added to the input box, to enter parts box dimensions.

Parts will be tried to fit in a frame crate or frame skid. If the part is too large to fit in any available crate, no new crate should be created but a warning that the added part will not fit in the shipment. 

If the parts box will fit in a crate, it will show up in the excel outputs (including the Part-List)

**Comment by fgasnier71** [comment]
[2021-02 Packing parts.pptx](https://github.com/treeDiM/MHBCrateLoadDesigner/files/6296815/2021-02.Packing.parts.pptx)

@JelmerDL 

1. Should I apply spacing / margin when computing space available in standard crate?
2. How do you compute max height of part list in skid?
I could use: 

Angle frame in skid is alpha = asin(widthSkid/widthFrame)
->Max parts box height = (SkidWidth - boxWidth)/tan(alpha)

Do you have a better / more precise formula?

3. Do we need to display this box graphically when successfully placed (will add half a day)?

**Comment by JelmerDL** [comment]
@fgasnier71 
1. Yes, same as frame margin (to compensate for inaccuracies).
2. Like this: (I'm terrible at this, so please check):
checkWidth = skidWidth * 0,667
checkHeight = skidHeight - 450
alpha = tan(checkHeight/checkWidth)
Max boxHeight = (checkWidth - boxWidth) / tan(alpha)

3. Yes, please.

**Comment by fgasnier71** [comment]
@JelmerDL 
Can you confirm that:
1. part box is stored in the first crate/skid where it fits and the user is not asked if he has a preference regarding the crate.
2. sanity check warning is issued when either:
- no part box is included in delivery,
- the software was unable to fit a defined part box in any crate.
- a frame crate has more layers than normally allowed.
3. Sanity check form is always issued before exporting.

**Comment by JelmerDL** [comment]
@fgasnier71 

> 1. part box is stored in the first crate/skid where it fits and the user is not asked if he has a preference regarding the crate.
Yes, no objection.

Additionally, the part box should also be filled out on the Parts-list (table of contents) excel sheet for the corresponding crate(s):
![image](https://user-images.githubusercontent.com/78344754/114510619-28687200-9c37-11eb-9a30-f46f20089929.png)

> 2. sanity check warning is issued when either:
 
> * no part box is included in delivery,
> * the software was unable to fit a defined part box in any crate.
> * a frame crate has more layers than normally allowed.

Yes, and overrideable by user.

> 3. Sanity check form is always issued before exporting.

If that is easier to code, no objections. However, it might be more user-friendly if no check form shows when there are no errors found.

**Comment by JelmerDL** [comment]
Regarding #7, I haven't been able to fit a part box (default size, suggested by the program itself), even when I have ample space in a crate available like this:

![image](https://user-images.githubusercontent.com/78344754/116543045-a8f0c900-a8ed-11eb-8037-f6dade629e1a.png)

When I make the part box really tiny (eg. 1x1x1mm), it still gives a warning and doesn't place the box.

**Comment by fgasnier71** [comment]
This issue is not closed.
I tried to explain that in the release details: 
_**> Part boxes can be added in the project but are not saved and not currently inserted in the crates.**_
