### ISSUE TITLE
Manual layer editing

### ISSUE THREAD

**Issue by JelmerDL** [treeDiM/MHBCrateLoadDesigner#8]
For frame crates it should be possible to manually force an extra layer. For example if the software comes up with a solution of 1 crate with 12 layers and 1 crate with 1 layer, the user should be able to manually force a 13th layer in the first crate thus saving a crate.

An alert should be added to warn the user that there are more layers than usual in the crate.

**Comment by fgasnier71** [comment]
Users can now move layers from crate to crate...
Drag&drop might be implemented later.
